##Mamadou DIOUF

Health status with DNA sequence

HACKATHON

In [ ]:
import pandas as pd
import numpy as np
import random

In [ ]:
df = pd.read_csv('/content/health_data.csv')

In [ ]:
bases = ['A', 'T', 'C', 'G']

In [ ]:

from sklearn import preprocessing
pre = preprocessing.LabelEncoder()
pre.fit(bases)


LabelEncoder()

In [ ]:
df

Health_Status                                       DNA_Sequence
0       Mutation_Possible  TTAGGGCGGATCTGCCCTCGGTCCCTTGGGAGGATGGAGTGAGACA...
1                 Healthy  TTAGGGCTGTACAGATCATGGAAGTTAGAATCACAAGGTGTACAGA...
2                 Healthy  TTAGGGCCTTCATCCAGGATAACGGATGAACTCGATTTCCACAGGA...
3       Mutation_Possible  TTAGCGGTTCCCAACAGCGAAGCTACTATTCGGGGTCATCTTCAAT...
4                Stressed  TTAGGGTTCACTTTAAACGACCTGTGTAATAAAAAATCCATTAAGA...
...                   ...                                                ...
299995           Stressed  TTAGGGACCAAGCGCCAACTGCACAAACAACGACATCTTTTAACTA...
299996  Mutation_Possible  TTAGGGTCTGGTTCTACTAGCCAACGATCAATTGGCATGACGCCGC...
299997           Stressed  TTAGGGACCTCCGTTCAGATCGTATATATGTCTACTACAAATAGAT...
299998           Stressed  TTAGGGATAAACTGTCCGTAATTCGGTAAGAGTGGTTAACCCAGCG...
299999           Stressed  TTAGGGGATGACCCAACGGCCGCGGGGTGCCCGAGCTTTGGAGTCG...

[300000 rows x 2 columns]

In [ ]:
df['DNA_Sequence']

0         TTAGGGCGGATCTGCCCTCGGTCCCTTGGGAGGATGGAGTGAGACA...
1         TTAGGGCTGTACAGATCATGGAAGTTAGAATCACAAGGTGTACAGA...
2         TTAGGGCCTTCATCCAGGATAACGGATGAACTCGATTTCCACAGGA...
3         TTAGCGGTTCCCAACAGCGAAGCTACTATTCGGGGTCATCTTCAAT...
4         TTAGGGTTCACTTTAAACGACCTGTGTAATAAAAAATCCATTAAGA...
                                ...                        
299995    TTAGGGACCAAGCGCCAACTGCACAAACAACGACATCTTTTAACTA...
299996    TTAGGGTCTGGTTCTACTAGCCAACGATCAATTGGCATGACGCCGC...
299997    TTAGGGACCTCCGTTCAGATCGTATATATGTCTACTACAAATAGAT...
299998    TTAGGGATAAACTGTCCGTAATTCGGTAAGAGTGGTTAACCCAGCG...
299999    TTAGGGGATGACCCAACGGCCGCGGGGTGCCCGAGCTTTGGAGTCG...
Name: DNA_Sequence, Length: 300000, dtype: object

In [ ]:
len(df['DNA_Sequence'][3])

100

In [ ]:
df_lseq = [pre.transform(list(i)).tolist() for i in df['DNA_Sequence']]

In [ ]:
d = np.array(df_lseq)

In [ ]:
d

array([[3, 3, 0, ..., 0, 1, 2],
       [3, 3, 0, ..., 0, 1, 1],
       [3, 3, 0, ..., 2, 2, 2],
       ...,
       [3, 3, 0, ..., 1, 1, 3],
       [3, 3, 0, ..., 0, 2, 0],
       [3, 3, 0, ..., 0, 3, 1]])

In [ ]:
df_2 =pd.DataFrame(d)

In [ ]:
df_2.shape

(300000, 100)

In [ ]:
df_f =pd.concat([df['Health_Status'],df_2],axis=1)

In [ ]:
df_f

Health_Status  0  1  2  3  4  5  6  7  8  ...  90  91  92  93  94  \
0       Mutation_Possible  3  3  0  2  2  2  1  2  2  ...   0   0   1   3   3   
1                 Healthy  3  3  0  2  2  2  1  3  2  ...   0   1   2   0   1   
2                 Healthy  3  3  0  2  2  2  1  1  3  ...   2   2   0   1   1   
3       Mutation_Possible  3  3  0  2  1  2  2  3  3  ...   2   0   2   0   0   
4                Stressed  3  3  0  2  2  2  3  3  1  ...   0   2   1   0   2   
...                   ... .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..   
299995           Stressed  3  3  0  2  2  2  0  1  1  ...   3   3   1   3   2   
299996  Mutation_Possible  3  3  0  2  2  2  3  1  3  ...   1   0   0   0   0   
299997           Stressed  3  3  0  2  2  2  0  1  1  ...   2   3   3   1   2   
299998           Stressed  3  3  0  2  2  2  0  3  0  ...   2   2   0   1   3   
299999           Stressed  3  3  0  2  2  2  2  0  3  ...   3   0   1   0   1   

        95  96  97  98  99  
0        2   1   0   1   2  
1        1   3   0   1   1  
2        1   1   2   2   2  
3        2   2   2   0   0  
4        3   0   3   1   0  
...     ..  ..  ..  ..  ..  
299995   3   0   1   0   0  
299996   0   2   2   1   1  
299997   2   2   1   1   3  
299998   1   0   0   2   0  
299999   0   3   0   3   1  

[300000 rows x 101 columns]

In [ ]:
y = df_f['Health_Status']
X = df_f.drop(columns='Health_Status')

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,)

In [ ]:
X_train

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  \
254099   3   3   0   2   2   2   1   1   3   2  ...   2   2   3   2   2   1   
53461    3   3   0   2   2   2   0   2   3   1  ...   0   0   1   3   1   3   
247984   3   3   0   2   2   2   3   3   0   3  ...   1   1   2   1   0   1   
209067   3   3   0   2   2   2   1   3   2   1  ...   3   3   0   2   3   1   
185997   3   3   0   2   1   2   0   2   3   3  ...   0   0   0   0   1   0   
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
119879   3   3   0   2   2   2   2   1   2   3  ...   3   1   2   3   3   1   
259178   3   3   0   2   2   2   0   3   2   1  ...   3   3   1   2   3   2   
131932   3   3   0   2   2   2   2   2   0   0  ...   2   2   2   2   1   0   
146867   3   3   0   2   2   2   0   2   0   1  ...   2   2   1   0   1   1   
121958   3   3   0   2   2   2   3   1   1   1  ...   2   1   1   0   1   3   

        96  97  98  99  
254099   2   3   3   2  
53461    1   1   3   3  
247984   3   3   3   2  
209067   0   1   3   1  
185997   0   2   0   1  
...     ..  ..  ..  ..  
119879   0   1   0   1  
259178   1   2   3   2  
131932   2   3   1   0  
146867   3   2   1   1  
121958   2   0   3   0  

[240000 rows x 100 columns]

In [ ]:
from lightgbm import LGBMClassifier

In [ ]:
clf = LGBMClassifier(force_row_wise=True,n_estimators=300, num_leaves=20,boosting_type='dart',)
clf.fit(X_train, y_train)


[LightGBM] [Info] Total Bins 379
[LightGBM] [Info] Number of data points in the train set: 240000, number of used features: 95
[LightGBM] [Info] Start training from score -1.099963
[LightGBM] [Info] Start training from score -1.096302
[LightGBM] [Info] Start training from score -1.099575


LGBMClassifier(boosting_type='dart', force_row_wise=True, n_estimators=300,
               num_leaves=20)

In [ ]:
clf.score(X_train,y_train)

0.5417041666666667

In [ ]:
clf.score(X_test,y_test)

0.5388166666666667

In [ ]:
from sklearn.model_selection import cross_validate

In [ ]:
cv_results = cross_validate(LGBMClassifier(boosting_type='dart', force_row_wise=True, n_estimators=300,
               num_leaves=20), X, y, cv=3)

[LightGBM] [Info] Total Bins 379
[LightGBM] [Info] Number of data points in the train set: 200000, number of used features: 95
[LightGBM] [Info] Start training from score -1.099988
[LightGBM] [Info] Start training from score -1.095313
[LightGBM] [Info] Start training from score -1.100544
[LightGBM] [Info] Total Bins 379
[LightGBM] [Info] Number of data points in the train set: 200000, number of used features: 95
[LightGBM] [Info] Start training from score -1.099973
[LightGBM] [Info] Start training from score -1.095313
[LightGBM] [Info] Start training from score -1.100559
[LightGBM] [Info] Total Bins 379
[LightGBM] [Info] Number of data points in the train set: 200000, number of used features: 95
[LightGBM] [Info] Start training from score -1.099988
[LightGBM] [Info] Start training from score -1.095298
[LightGBM] [Info] Start training from score -1.100559


In [ ]:
cv_results['fit_time']

array([128.94469404, 126.46395493, 127.25433636])

In [ ]:
cv_results['score_time']

array([3.27193356, 3.57965612, 3.49674892])

In [ ]:
cv_results['test_score']

array([0.53966, 0.53985, 0.53766])

In [ ]:
[[0,0,0,0]]*0

[]